### ISSUE TITLE
Error: was unable to find a spot to create a popup

### ISSUE THREAD

**Issue by jonahfang** [carbon-steel/detour.nvim#15]
When I run `require("detour").Detour()` I get an error and cannot create the popup. Can you provide a return value of nil to the command when an error occurs, and provide an option to not display a prompt?

**Comment by carbon-steel** [comment]
This is a very interesting idea! I'll think about creating a `silent` option for the function :)

**Comment by carbon-steel** [comment]
Upon further thought, I've decided against adding a `silent` option for the plugin. The plugin was perhaps throwing too many errors before, but I think the plugin has been [improved](https://github.com/carbon-steel/detour.nvim/issues/16) and thus throws fewer error messages. The error messages provide an opportunity for bugs to be reported or to meaningfully point out user errors.
