### ISSUE TITLE
Unable to get a popup to work with `vim.lsp.buf.definiton`

### ISSUE THREAD

**Issue by JustBarnt** [carbon-steel/detour.nvim#32]
Are there any examples of using `Detour` for viewing a definition or looking at implementations because I have tried the following here and I cannot get it to work.

I'm sure I am overlooking something, but based off what I see in the docs with terminal windows I would expect something like this to work?

```lua
vim.kemap.set("n", "gd", function()
        require("detour").Detour()
        vim.lsp.buf.definition({
            reuse_win = false
        })
    end, { desc = "Goto Definition" })
```

**Comment by JustBarnt** [comment]
Ah nevermind, I have figured it out. I was not thinking fully through the order that things needed to happen.

Unlike the terminal example, I needed to call `vim.lsp.buf.definition({reuse_win = false})` before hand and then call `require('detour').Detour()` to redirect the call to detour.

**Comment by JustBarnt** [comment]
I will submit my final setup for using Detour for `vim.buf.lsp` actions into the examples though so that others will hopefully not make the same mistakes I did.

**Comment by carbon-steel** [comment]
Actually, I don't see anything wrong with this code.
```lua
vim.kemap.set("n", "gd", function()
        require("detour").Detour()
        vim.lsp.buf.definition({
            reuse_win = false
        })
    end, { desc = "Goto Definition" })
```
The call to `Detour` should open a popup showing the same buffer you were looking at. Calling `vim.lsp.buf.definition({reuse_win=false})` should go-to-definition using the current window (which should be the popup). Is that not what happens?

**Comment by JustBarnt** [comment]
No, it was just highlighting the symbol as if I had searched it. Not sure why moving `Detour` after is working. But I am also in the process of refactoring my configuration. So there very well could be something else interfering with that that I am unaware of.

**Comment by carbon-steel** [comment]
FYI, I wrote down instructions on running the plugin on a clean (no config) instance of neovim here: https://github.com/carbon-steel/detour.nvim/issues/21#issuecomment-1851124805

I also would recommend using the most recent version of the plugin as well. There have been improvements :)

**Comment by JustBarnt** [comment]
Thanks! I'll make sure to take a look at this while I am refactoring my config! I will also double check that I have detour updated as well!

**Comment by carbon-steel** [comment]
Ping. I've been wondering how this turned out?

**Comment by JustBarnt** [comment]
@carbon-steel Sorry I haven't had a change to work on my new config for a couple weeks, I'm just started back up on it this weekend let me setup Detour again and check!

**Comment by JustBarnt** [comment]
@carbon-steel Good news! I can confirm it was something within my old config!

**Comment by JustBarnt** [comment]
@carbon-steel I did have a secondary question though and this could something I've overlooked on my end. But is there way to close the popup just by using "q" similar to how Lazy UI or Mason can be closed?

**Comment by carbon-steel** [comment]
Personally, I've mapped `Q` (capitalized) to `vim.cmd.close`. it works well for me. Not just in popups. In general.

**Comment by JustBarnt** [comment]
@carbon-steel ive never thought about that... thank you for the suggestion! I'm gonna implement that as well!

**Comment by JustBarnt** [comment]
@carbon-steel I found the cause behind my initial issue as I was working on my new config last night. There was a snippet of code I've been using for my LSP that I found in a config I had looked a long time ago, that always jumps me to the first definition available.

It uses `vim.lsp.util.jump_to_location` instead of `vim.lsp.buf.definition`

But I am not sure if this is really an issue that Detour would be concerned with. If you think this is something that Detour should deal with, I can re-open this as well, or if you are open to PR's I can take a stab at fixing it as well. 

This is the current way I am overriding `textDocument/definition` handler

```lua
vim.lsp.handlers['textDocument/definition'] = function(_, result)
    if not result or vim.tbl_isempty(result) then
        print("[LSP] Could not find definition")
    end

    if vim.tbl_islist(result) then
        vim.lsp.util.jump_to_location(result[1], "utf-8", false)
    else
        vim.lsp.util.jump_to_location(result, "utf-8", false)
    end
    require('detour').Detour()
end
```

**Comment by carbon-steel** [comment]
I just tried running the code from https://github.com/carbon-steel/detour.nvim/issues/32#issuecomment-1898808595 with the keymap from https://github.com/carbon-steel/detour.nvim/issues/32#issue-2064211517 and they seem to work fine together. A popup opens up with the definition of the function my cursor is on.

I don't quite see any issues with either pieces of code. In my mind, it should all work as expected. If you think there is a way that the detour plugin could be improved, I'm happy to work with you on a PR. Are there more details you could share to help me understand more about the issue? Are you using a recent version of Neovim?

**Comment by carbon-steel** [comment]
On a separate note, if you want to checkout the code, I recommend staying on the `dev` branch as that is the most up-to-date code.
