### ISSUE TITLE
Check the focusing behavior of popup windows

### ISSUE THREAD

**Issue by carbon-steel** [carbon-steel/detour.nvim#4]
The popups don't seem to always get the effect of being the focused window. I've seen this with my colorscheme.

Another example: https://www.reddit.com/r/neovim/comments/17tu64y/comment/k91dv1k/?utm_source=share&utm_medium=web2x&context=3

**Comment by jonahfang** [comment]
This problem still exists in dev branch!

**Comment by carbon-steel** [comment]
I realized the problem was my color scheme :P
