### ISSUE TITLE
Use Detour for `:h`

### ISSUE THREAD

**Issue by JustBarnt** [carbon-steel/detour.nvim#42]
I've been trying to think of how I could use detour to always open up `:h` in a detour popup. Any ideas? I was thinking by event but I don't see any event that I think would correlate to help being opened.

**Comment by JustBarnt** [comment]
I just found this [comment](https://www.reddit.com/r/neovim/s/OL1IkISQ6y) so I'll keep you posted if this works instead!

**Comment by carbon-steel** [comment]
I gave it a try. Here is what I came up with:

```lua
vim.api.nvim_create_user_command("H", function (args)
    local file = args.args
    vim.cmd.h(file)
    local help_win = vim.api.nvim_get_current_win()

    local ok = require('detour').Detour()
    if ok then
        vim.api.nvim_win_close(help_win, false)
    end
end, { nargs = 1 })
```

If you run this code and then run `:H autocmd`, you should get the help page for autocmd in a detour popup.

**Comment by JustBarnt** [comment]
@carbon-steel Thanks! I'll give this a try I spent a good part of the weekend trying to figure something out, that Reddit post worked for what that particular person wanted but not for me. Haha.

**Comment by JustBarnt** [comment]
@carbon-steel This is fantastic! and I have a couple ideas I'm gonna in combination with the other post as well! I'll keep you updated! But I'll close this as it does 100% answer my question!

**Comment by carbon-steel** [comment]
I think it looks pretty good! Can I ask why you call `vim.cmd.h` for the user when checking `if filetype == "help"` means you want this code to run after the user opens a help file themselves?

Like, how about:
```lua
-- Open help files only in a float
vim.api.nvim_create_autocmd("BufWinEnter", {
    pattern = "*",
    callback = function(event)
        local filetype = vim.bo[event.buf].filetype

        if filetype == "help" then
            -- Get the newly opened help window
            -- and attempt to open a Detour() float
            local help_win = vim.api.nvim_get_current_win()
            local ok = require("detour").Detour()

            -- If we successfully create a float of the help file
            -- Close the split
            if ok then
                vim.api.nvim_win_close(help_win, false)
            end
        end
    end,
})
```

**Comment by JustBarnt** [comment]
@carbon-steel Because I got distracted and only half completed the `autocmd`. If the help docs are `.md` and not `.txt`, Neovim doesn't appear to consider the filetype to be 'help'. So when I try to open `.md` docs like `Detour` - it still opens in a split. 

So I meant to say `if filetype == 'help' or 'markdown' then ... end`

Unless you have an idea how to handle that, which doesn't require the extra, then I am all for it!

**Comment by JustBarnt** [comment]
Actually this should work just fine.

```lua
-- Open help files only in a float
vim.api.nvim_create_autocmd("BufWinEnter", {
    pattern = "*",
    callback = function(event)
        local filetype = vim.bo[event.buf].filetype

        if filetype == 'markdown' then filetype = 'help' end

        -- Only run if the filetype is a help file
        if filetype == "help" then
            -- Get the newly opened help window
            -- and attempt to open a Detour() float
            local help_win = vim.api.nvim_get_current_win()
            local ok = require("detour").Detour()

            -- If we successfully create a float of the help file
            -- Close the split
            if ok then
                vim.api.nvim_win_close(help_win, false)
            end
        end
    end,
})
```

**Comment by JustBarnt** [comment]
@carbon-steel If you think this is something others using Detour might be interested in setting up I can write an example tonight and submit a PR

**Comment by carbon-steel** [comment]
Yeah! I'd appreciate a PR for an example :)
