### ISSUE TITLE
util pollutes the global lua module namepsace

### ISSUE THREAD

**Issue by lettertwo** [carbon-steel/detour.nvim#6]
If a user has their own lua module called 'util', it will be in conflict with the 'util' module in this plugin.

Maybe it should be namespaced under detour.util?

**Comment by carbon-steel** [comment]
That's a huge problem! Thanks for bringing it to my attention. I've changed the `util.lua` file to `detour_util.lua` to fix the issue. Let me know if this fixes the issue for you :)
