### ISSUE TITLE
Add option 'allow_nested = false/true'

### ISSUE THREAD

**Issue by jonahfang** [carbon-steel/detour.nvim#9]
I prefer one layer of popup window, I do like this now:
```lua

        { "zp", mode = {"n"}, function()
            if w.is_floating() then
                return
            end -- no nested popup
            if not w.is_file() then
                return
            end
            require("detour").Detour()
        end},
```

**Comment by carbon-steel** [comment]
Thanks for bringing this up. Currently, I prefer not to implement an option into the plugin to alter its behavior when it is possible for users to accomplish the desired behavior (eg, preventing nesting) in a small amount of code in their config. My vision for the plugin is to provide a minimal interface that can be used flexibly. Your example code is the kind of configuration that I intend for users to create for themselves.

That being said, creating a place where users can share these sample codes is on my todo list.
